service: tfr-scraper

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs24.x
  environment:
    MONGODB_USER: ${file(./config.${opt:stage, 'prod'}.json):MONGODB_USER}
    MONGODB_PASSWORD: ${file(./config.${opt:stage, 'prod'}.json):MONGODB_PASSWORD}
    MONGODB_HOST: ${file(./config.${opt:stage, 'prod'}.json):MONGODB_HOST}
    NMS_API_HOST: ${file(./config.${opt:stage, 'prod'}.json):NMS_API_HOST}
    NMS_API_KEY: ${file(./config.${opt:stage, 'prod'}.json):NMS_API_KEY}
    NMS_API_SECRET: ${file(./config.${opt:stage, 'prod'}.json):NMS_API_SECRET}

functions:
  scraper:
    handler: handler.scraper
    timeout: 300 # 5 minutes
    memorySize: 512
    events:
      - schedule: rate(15 minutes)
  query:
    handler: handler.query
    memorySize: 256
    events:
      - httpApi:
          method: GET
          path: /api/tfr

plugins:
  - serverless-esbuild
